on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 0-1,6"
jobs:
  deploy_github_page:
    name: deploy to github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm install
      - name: Run webscrapers
        run: node ./scripts/buildData.mjs
        env:
          NY_TIMES_API_KEY: ${{ secrets.NY_TIMES_API_KEY }}
      - run: pnpm run generate
      - run: touch .output/public/.nojekyll
      - name: Setup Git repo for deployment
        run: |
          git init
          git checkout -b master
        working-directory: .output/public
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: .output/public
      - name: Commit build to github pages repo
        run: |
          git config -l
          git add -A
          git commit -S -m "deploy $(date)"
          git push -f git@github.com:comparelist/comparelist.github.io.git master
        working-directory: .output/public
